//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smtirpz
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallsDB
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int ContractNum { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public int DestinationID { get; set; }
        public long Duration { get; set; }
    }
}
