//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smtirpz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractNumber
    {
        public int Id { get; set; }
        public int AbonentAdressID { get; set; }
        public double Discount { get; set; }
        public System.DateTime StartTime { get; set; }
        public int DeviseCount { get; set; }
        public int Blockrator { get; set; }
        public double Cedit { get; set; }
    }
}
